// Code generated by go generate; DO NOT EDIT.

package example

import "fmt"


var (
    ShippingMethodUnknown = ShippingMethod{ "" }
    ShippingMethodUPSNextDayAir = ShippingMethod{ "ups_1DA" }
    ShippingMethodUPS2DayAir = ShippingMethod{ "ups_2DA" }
    ShippingMethodUPSGround = ShippingMethod{ "ups_GND" }
)

type shippingmethodvalue string

// ShippingMethod simulates an enum with available values.
type ShippingMethod struct {
   value shippingmethodvalue
}

// String returns the display name of the ShippingMethod.
func (gt ShippingMethod) String() string {
    return shippingMethodValues[string(gt.value)]
}

// Value returns the value of the ShippingMethod.
func (gt ShippingMethod) Value() string {
    return string(gt.value)
}

// ParseShippingMethod parses a value into a ShippingMethod.
// The error can be ignored if the zero value is desireable.
func ParseShippingMethod(val string) (ShippingMethod, error) {
    if _, ok := shippingMethodValues[val]; ok {
        return ShippingMethod{ shippingmethodvalue(val) },nil
    }
    return ShippingMethod{}, fmt.Errorf("failed parsing ShippingMethod: invalid value %s", val)
}

